export const FETCH_ACCOUNT_INFO_DATA = "FETCH_ACCOUNT_INFO_DATA";
export const FETCH_ACCOUNT_INFO_DATA_SUCCESS =
  "FETCH_ACCOUNT_INFO_DATA_SUCCESS";
export const FETCH_ACCOUNT_INFO_DATA_FAIL = "FETCH_ACCOUNT_INFO_DATA_FAIL";
export const CHANGE_ACCOUNT_NAME = "CHANGE_ACCOUNT_NAME";
export const CHANGE_ACCOUNT_PASSWORD = "CHANGE_ACCOUNT_PASSWORD";
