export const FETCH_CANDLE_DATA = "FETCH_CANDLE_DATA";
export const FETCH_CANDLE_DATA_SUCCESS = "FETCH_CANDLE_DATA_SUCCESS";
export const FETCH_CANDLE_DATA_FAIL = "FETCH_CANDLE_DATA_FAIL";
export const MODIFY_CANDLE_DATA = "MODIFY_CANDLE_DATA";
export const RESET_CANDLE_DATA = "RESET_CANDLE_DATA";
