export const CONNECT_WEBSOCKET = "CONNECT_WEBSOCKET";
export const CONNECT_WEBSOCKET_SUCCESS = "CONNECT_WEBSOCKET_SUCCESS";
export const CONNECT_WEBSOCKET_FAIL = "CONNECT_WEBSOCKET_FAIL";
export const RESET_WEBSOCKET = "RESET_WEBSOCKET";
